/* Generated by scripts/build-translations.mjs. Do not edit by hand. */
import as from "./as.json";
import bn from "./bn.json";
import brx from "./brx.json";
import doi from "./doi.json";
import en from "./en.json";
import gu from "./gu.json";
import hi from "./hi.json";
import kn from "./kn.json";
import kok from "./kok.json";
import ks from "./ks.json";
import mai from "./mai.json";
import ml from "./ml.json";
import mni from "./mni.json";
import mr from "./mr.json";
import ne from "./ne.json";
import or from "./or.json";
import pa from "./pa.json";
import sa from "./sa.json";
import sat from "./sat.json";
import sd from "./sd.json";
import ta from "./ta.json";
import te from "./te.json";
import ur from "./ur.json";

export type Dictionary = Record<string, string>;

export const DICTIONARIES: Record<string, Dictionary> = {
  "as": as,
  "bn": bn,
  "brx": brx,
  "doi": doi,
  "en": en,
  "gu": gu,
  "hi": hi,
  "kn": kn,
  "kok": kok,
  "ks": ks,
  "mai": mai,
  "ml": ml,
  "mni": mni,
  "mr": mr,
  "ne": ne,
  "or": or,
  "pa": pa,
  "sa": sa,
  "sat": sat,
  "sd": sd,
  "ta": ta,
  "te": te,
  "ur": ur,
};
