import {
  VoiceAiDependencies,
  VoiceDescriptionInput,
  VoiceDescriptionOutput,
} from "../types/voice-ai.types";
import { VoiceAiError, DescriptionGenerationError } from "../errors/voice-ai.errors";

const noopLogger = {
  info: () => {},
  warn: () => {},
  error: () => {},
};

/**
 * The single function the backend developer needs to call:
 *
 *   const result = await processVoiceDescription(
 *     { audio: req.file.buffer, mimeType: req.file.mimetype, category: req.body.category },
 *     dependencies,
 *   );
 *
 * See voice_ai_integration.md for the full integration guide, and
 * pipeline/factory.ts for how to build `dependencies` from environment
 * variables (real providers, or mocks while BHASHINI is pending).
 *
 * Pipeline:
 *   audio -> STT (+ automatic language detection)
 *         -> [regional -> English translation, skipped if already English]
 *         -> Gemini: English description generation
 *         -> English -> Hindi translation (of the FINAL Gemini description,
 *            never independently generated by Gemini)
 */
export async function processVoiceDescription(
  input: VoiceDescriptionInput,
  deps: VoiceAiDependencies,
): Promise<VoiceDescriptionOutput> {
  const logger = deps.logger ?? noopLogger;

  logger.info("voice-ai: starting pipeline", { category: input.category, audioBytes: input.audio?.length });

  try {
    const sttResult = await deps.sttService.transcribe(input.audio, input.mimeType);
    logger.info("voice-ai: stt complete", { detectedLanguage: sttResult.language });

    const transcript = sttResult.text;
    const detectedLanguage = sttResult.language;

    const englishTranscript =
      detectedLanguage === "en"
        ? transcript
        : await deps.translationService.translate(transcript, detectedLanguage, "en");

    if (detectedLanguage !== "en") {
      logger.info("voice-ai: regional -> English translation complete");
    }

    const descriptionEn = await deps.descriptionService.generateDescription(englishTranscript, input.category);
    logger.info("voice-ai: description generation complete");

    const descriptionHi = await deps.translationService.translate(descriptionEn, "en", "hi");
    logger.info("voice-ai: English -> Hindi translation complete");

    return { transcript, descriptionEn, descriptionHi, detectedLanguage };
  } catch (err) {
    if (err instanceof VoiceAiError) {
      logger.error(`voice-ai: pipeline failed at stage "${err.stage}"`, { message: err.message });
      throw err;
    }
    logger.error("voice-ai: pipeline failed with an unexpected error", { err });
    throw new DescriptionGenerationError("Unexpected error in voice AI pipeline", err);
  }
}
